Fix error causing game not to start
Traceback (most recent call last):
  File "/Users/ryder/Desktop/91883 and 91884/Hangman/hangmangui.py", line 158, in <module>
    game = Game(window)
TypeError: __init__() takes 1 positional argument but 2 were given